#Don't close the player after finishing the video
keep-open=yes
fs=no
geometry=50%:50%

#The last position of your video is saved when quitting mpv
save-position-on-quit=yes

#Start mpv with a % smaller resolution of your screen
autofit=50%

#Audio language priority
alang=ja,jp,jpn,en,eng

#Subtitle language priority
slang=en,eng,vn,vi

#Forces showing subtitles while seeking through the video
demuxer-mkv-subtitle-preroll=yes

#Backward compatibility for vsfilter fansubs
sub-ass-vsfilter-blur-compat=yes

#Fixes subtitle timing for gaps smaller than 210ms (works with PGS subtitles)
sub-fix-timing=yes

#Load external subtitles with (almost) the same name as the video 
sub-auto=fuzzy

#Output format of screenshots
screenshot-format=png

#Same output bitdepth as the video
#Set it "no" if you want to save disc space
screenshot-high-bit-depth=yes

#Compression of the PNG picture (1-9)
#Higher value means better compression, but takes more time
screenshot-png-compression=1

#Quality of JPG pictures (0-100)
#Higher value means better quality
screenshot-jpeg-quality=100
#Output directory
screenshot-directory="~/Pictures"

#Name format you want to save the pictures
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

#Force seeking (if seeking doesn't work)
force-seekable=yes