plugins: fetchart embedart convert mpdupdate
import:
  move: yes
match:
  strong_rec_thresh: 0.15
fetchart:
  maxwidth: 1024
  max_filesize: 1000000
  sources:
    - coverart: release
    - itunes
    - coverart: releasegroup
    - filesystem
mpd:
    host: localhost
    port: 6600

